
services:
  db:
    image: postgres:14
    container_name: cafeteria_db # Nome do container, pode ser o que você preferir
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cafeteria_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cafeteria_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cafeteria
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build: ./frontend
    container_name: cafeteria_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: